---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  profiles:
    active: ${ACTIVE_PROFILE}
    default: development

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

#user:
#  email: "hexlet@example.com"
#  password: "qwerty"
#
## format: low case, no spaces - use _ instead
#initial:
#  task-statuses: draft, to_review, to_be_fixed, to_publish, published
#  labels: bug, feature

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

sentry:
  dsn: https://40038e15a5654794efaeaa9de2d31185@o4507385692946432.ingest.us.sentry.io/4507390089953280
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0