---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  output:
    ansi:
      enabled: always
  profiles:
    default: production

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

user:
  email: hexlet@example.com
  password: qwerty

# format: low case, no spaces - use _ instead
task-statuses: >
    draft,
    to_review,
    to_be_fixed,
    to_publish,
    published

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
