---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: "production"
  datasource:
    url: "jdbc:h2:mem:project"
    driver-class-name: "org.h2.Driver"

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
