---

spring:
  datasource:
    url: "jdbc:h2:mem:project"
    driver-class-name: "org.h2.Driver"
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false

user:
  email: test@test.com
  password: test
