---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: "production"

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

admin:
  email: "hexlet@example.com"
  password: "qwerty"

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem